--- #YAML:1.0
name: HTTP-Proxy
version: 0.20
author:
  - Philippe "BooK" Bruhat <book@cpan.org>
abstract: A pure Perl HTTP proxy
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
